import datetime

from sqlalchemy import Column, Integer, String, BigInteger, Boolean, Identity, DateTime
from database import Base, IngestionBase


class Diameter(Base):
    __tablename__ = "diameter"
    id = Column(BigInteger, Identity(start=1, cycle=True), primary_key=True, nullable=False)
    frames_list = Column(String(64), nullable=False)
    time_epoch = Column(BigInteger, nullable=False, index=True)
    useconds_epoch = Column(Integer, nullable=False)
    src_ip = Column(String(15), nullable=False)
    dst_ip = Column(String(15), nullable=False)
    request = Column(Boolean, nullable=False)
    command_code = Column(Integer, nullable=False, index=True)
    hop_by_hop_id = Column(BigInteger, nullable=False)
    end_to_end_id = Column(BigInteger, nullable=False, index=True)
    result_code = Column(Integer, nullable=True)
    exp_result_code = Column(Integer, nullable=True)
    origin_host = Column(String, nullable=True)
    origin_realm = Column(String, nullable=True)
    destination_host = Column(String, nullable=True)
    destination_realm = Column(String, nullable=True)
    msisdn = Column(String(32), nullable=True, index=True)
    imsi = Column(String(32), nullable=True, index=True)
    pcap_filename = Column(String, nullable=False, index=True)


class GsmMap(Base):
    __tablename__ = "ss7map"
    id = Column(BigInteger, Identity(start=1, cycle=True), primary_key=True, nullable=False)
    frames_list = Column(String(64), nullable=False)
    time_epoch = Column(BigInteger, nullable=False, index=True)
    useconds_epoch = Column(Integer, nullable=False)
    src_ip = Column(String(15), nullable=True)
    dst_ip = Column(String(15), nullable=True)
    mtp3_opc = Column(Integer, nullable=False)
    mtp3_dpc = Column(Integer, nullable=False)
    tcap_mess_type = Column(String(16), nullable=False)
    tcap_tid = Column(BigInteger, nullable=True, index=True)
    tcap_otid = Column(BigInteger, nullable=True, index=True)
    tcap_dtid = Column(BigInteger, nullable=True, index=True)
    tcap_result = Column(Integer, nullable=True)
    gsm_op_code = Column(Integer, nullable=True, index=True)
    gsm_component = Column(Integer, nullable=True)
    gsm_error_code = Column(Integer, nullable=True)
    msisdn = Column(String(32), nullable=True, index=True)
    imsi = Column(String(32), nullable=True, index=True)
    pcap_filename = Column(String, nullable=False, index=True)


class Http(Base):
    __tablename__ = "http"
    id = Column(BigInteger, Identity(start=1, cycle=True), primary_key=True, nullable=False)
    frames_list = Column(String(64), nullable=False)
    time_epoch = Column(BigInteger, nullable=False, index=True)
    useconds_epoch = Column(Integer, nullable=False)
    src_ip = Column(String(15), nullable=False, index=True)
    src_port = Column(Integer, nullable=False, index=True)
    dst_ip = Column(String(15), nullable=False, index=True)
    dst_port = Column(Integer, nullable=False, index=True)
    tcp_sequence = Column(BigInteger, nullable=False)
    tcp_acknowledge = Column(BigInteger, nullable=False)
    type = Column(String(10), nullable=False)
    http_is_request = Column(Boolean, nullable=False)
    http_response_in = Column(BigInteger, nullable=True)
    http_request_method = Column(String(10), nullable=True)
    http_request_uri = Column(String(256), nullable=True)
    http_content_type = Column(String(128), nullable=True)
    http_content_length = Column(Integer, nullable=True)
    http_response_code = Column(Integer, nullable=True)
    smpp_src_addr = Column(String(32), nullable=True, index=True)
    smpp_dst_addr = Column(String(32), nullable=True, index=True)
    smpp_seq_number = Column(BigInteger, nullable=True)
    tcap_otid = Column(BigInteger, nullable=True)
    tcap_dtid = Column(BigInteger, nullable=True)
    camel_orig_address = Column(String(32), nullable=True)
    camel_dest_address = Column(String(32), nullable=True)
    msisdn = Column(String(32), nullable=True, index=True)
    imsi = Column(String(32), nullable=True, index=True)
    diam_e2e_id = Column(BigInteger, nullable=True)
    diam_session_id = Column(String, nullable=True)
    diam_result_code = Column(Integer, nullable=True)
    diam_origin_host = Column(String, nullable=True)
    diam_origin_realm = Column(String, nullable=True)
    diam_destination_host = Column(String, nullable=True)
    diam_destination_realm = Column(String, nullable=True)
    pcap_filename = Column(String, nullable=False, index=True)


class Smpp(Base):
    __tablename__ = "smpp"
    id = Column(BigInteger, Identity(start=1, cycle=True), primary_key=True, nullable=False)
    frames_list = Column(String(64), nullable=False)
    time_epoch = Column(BigInteger, nullable=False, index=True)
    useconds_epoch = Column(Integer, nullable=False)
    src_ip = Column(String(15), nullable=False, index=True)
    dst_ip = Column(String(15), nullable=False, index=True)
    command_id = Column(String(16), primary_key=True, nullable=False)
    sequence_number = Column(Integer, primary_key=True, nullable=False)
    source_addr = Column(String(32), nullable=True, index=True)
    destination_addr = Column(String(32), nullable=True, index=True)
    command_status = Column(String(32), nullable=True)
    pcap_filename = Column(String, nullable=False, index=True)

class Sip(Base):
    __tablename__ = "sip"
    id = Column(BigInteger, Identity(start=1, cycle=True), primary_key=True, nullable=False)
    frames_list = Column(String(64), nullable=False)
    time_epoch = Column(BigInteger, nullable=False, index=True)
    useconds_epoch = Column(Integer, nullable=False)
    src_ip = Column(String(15), nullable=False, index=True)
    dst_ip = Column(String(15), nullable=False, index=True)
    method = Column(String(10), nullable=True, index=True)
    status_code = Column(Integer, nullable=True)
    status_line = Column(String, nullable=True)
    call_id = Column(String(128), nullable=False, index=True)
    from_user = Column(String(32), nullable=True, index=True)
    from_original = Column(String(32), nullable=True)
    to_user = Column(String(32), nullable=True, index=True)
    to_original = Column(String(32), nullable=True)
    supported = Column(String(64), nullable=True)
    require = Column(String(64), nullable=True)
    sdp_o_sessionid = Column(String(32), nullable=True)
    sdp_o_version = Column(String(32), nullable=True)
    pcap_filename = Column(String, nullable=False, index=True)

class Gtp(Base):
    __tablename__ = "gtp"
    id = Column(BigInteger, Identity(start=1, cycle=True), primary_key=True, nullable=False)
    frames_list = Column(String(64), nullable=False)
    time_epoch = Column(BigInteger, nullable=False, index=True)
    useconds_epoch = Column(Integer, nullable=False)
    src_ip = Column(String(15), nullable=False, index=True)
    dst_ip = Column(String(15), nullable=False, index=True)
    gtp_version = Column(String(5), nullable=False)
    gtp_message = Column(String, nullable=False, index=True)
    gtp_teid = Column(BigInteger, nullable=False)
    gtp_cause = Column(String, nullable=True)
    gtp_seq_number = Column(BigInteger, nullable=True, index=True)
    imsi = Column(String(32), nullable=True, index=True)
    msisdn = Column(String(32), nullable=True, index=True)
    pcap_filename = Column(String, nullable=False, index=True)

class Camel(Base):
    __tablename__ = "camel"
    id = Column(BigInteger, Identity(start=1, cycle=True), primary_key=True, nullable=False)
    frames_list = Column(String(64), nullable=False)
    time_epoch = Column(BigInteger, nullable=False, index=True)
    useconds_epoch = Column(Integer, nullable=False)
    src_ip = Column(String(15), nullable=True)
    dst_ip = Column(String(15), nullable=True)
    mtp3_opc = Column(Integer, nullable=True, index=True)
    mtp3_dpc = Column(Integer, nullable=True, index=True)
    tcap_tid = Column(BigInteger, nullable=True, index=True)
    tcap_otid = Column(BigInteger, nullable=True, index=True)
    tcap_dtid = Column(BigInteger, nullable=True, index=True)
    tcap_mess_type = Column(String(64), nullable=False)
    gsm_cld_party_bcd_num = Column(String(16), nullable=True)
    called_party_number_digits = Column(String(16))
    calling_party_number_digits = Column(String(16))
    msisdn = Column(String(32), nullable=True, index=True)
    imsi = Column(String(32), nullable=True, index=True)
    camel_local = Column(Integer, nullable=True)
    camel_calling_party_number = Column(String(32))
    camel_called_party_number = Column(String(32))
    pcap_filename = Column(String, nullable=False, index=True)


class HttpOcs(Base):
    __tablename__ = "http_ocs"
    id = Column(BigInteger, Identity(start=1, cycle=True), primary_key=True, nullable=False)
    frames_list = Column(String(64), nullable=False)
    time_epoch = Column(BigInteger, nullable=False, index=True)
    useconds_epoch = Column(Integer, nullable=False)
    src_ip = Column(String(15), nullable=False, index=True)
    src_port = Column(Integer, nullable=False, index=True)
    dst_ip = Column(String(15), nullable=False, index=True)
    dst_port = Column(Integer, nullable=False, index=True)
    tcp_sequence = Column(BigInteger, nullable=False)
    tcp_acknowledge = Column(BigInteger, nullable=False)
    http_is_request = Column(Boolean, nullable=False)
    http_response_in = Column(BigInteger, nullable=True)
    http_request_method = Column(String(10), nullable=True)
    http_request_uri = Column(String(256), nullable=True)
    http_content_type = Column(String(128), nullable=True)
    http_content_length = Column(Integer, nullable=True)
    http_response_code = Column(Integer, nullable=True)
    type = Column(String(32), nullable=False)
    operation_id = Column(Integer, nullable=True)
    cdpa = Column(String(32), nullable=True)
    msisdn = Column(String(32), nullable=True, index=True)
    rdn = Column(String(32), nullable=True)
    period_duration = Column(Integer, nullable=True)
    call_active = Column(Boolean, nullable=True)
    start_time = Column(String(32), nullable=True)
    end_time = Column(String(32), nullable=True)
    status = Column(String(128), nullable=True)
    status_code = Column(Integer, nullable=True)
    max_call_period_duration= Column(Integer, nullable=True)
    dtmf_route = Column(String(32), nullable=True)
    req_type = Column(String(10), nullable=True)
    shadow_number = Column(String(32), nullable=True)
    called = Column(String(32), nullable=True, index=True)
    calling = Column(String(32), nullable=True, index=True)
    msrn = Column(String(32), nullable=True)
    phone = Column(String(32), nullable=True, index=True)
    code = Column(Integer, nullable=True)
    result = Column(Integer, nullable=True)
    temp_cdpa = Column(String(32), nullable=True)
    dual_num = Column(String(32), nullable=True)
    mcc = Column(Integer, nullable=True)
    mnc = Column(Integer, nullable=True)
    imsi = Column(String(32), nullable=True, index=True)
    pcap_filename = Column(String, nullable=False, index=True)


class HttpSS7(Base):
    __tablename__ = "http_ss7"
    id = Column(BigInteger, Identity(start=1, cycle=True), primary_key=True, nullable=False)
    frames_list = Column(String(64), nullable=False)
    time_epoch = Column(BigInteger, nullable=False, index=True)
    useconds_epoch = Column(Integer, nullable=False)
    src_ip = Column(String(15), nullable=False, index=True)
    src_port = Column(Integer, nullable=False, index=True)
    dst_ip = Column(String(15), nullable=False, index=True)
    dst_port = Column(Integer, nullable=False, index=True)
    tcp_sequence = Column(BigInteger, nullable=False)
    tcp_acknowledge = Column(BigInteger, nullable=False)
    http_is_request = Column(Boolean, nullable=False)
    http_response_in = Column(BigInteger, nullable=True)
    http_request_method = Column(String(10), nullable=True)
    http_request_uri = Column(String(256), nullable=True)
    http_content_type = Column(String(128), nullable=True)
    http_content_length = Column(Integer, nullable=True)
    http_response_code = Column(Integer, nullable=True)
    type = Column(String(32), nullable=False, index=True)
    msisdn_orig = Column(String(32), nullable=True, index=True)
    msisdn_dest = Column(String(32), nullable=True, index=True)
    msc = Column(String(32), nullable=True)
    sccp_cd_adr = Column(String(32), nullable=True)
    imsi = Column(String(32), nullable=True, index=True)
    session_id = Column(String(16), nullable=True)
    text = Column(String(255), nullable=True)
    udhi = Column(Boolean, nullable=True)
    pcap_filename = Column(String, nullable=False, index=True)


class IngestionQueue(IngestionBase):
    __tablename__ = "ingestion_queue"
    id = Column(BigInteger, Identity(start=1, cycle=True), primary_key=True, nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    filename = Column(String(255), nullable=True)
    not_processed = Column(Integer, nullable=False, index=True)
    owner = Column(String(255), nullable=True)
    pid = Column(Integer, nullable=False, index=True)
    processed = Column(Integer, nullable=False, index=True)
    processed_at = Column(DateTime, default=datetime.datetime.utcnow)
    processing_at = Column(DateTime, default=datetime.datetime.utcnow)
    state = Column(Integer, nullable=False, index=True)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow)
    ingestion_instance_id = Column(Integer, nullable=False, index=True)
